Auctionator.lua, Auctionator.toc, AuctionatorConfig.lua, AuctionatorConfig.xml
* bumped TOC for next release
* added FAQ link to now more readable about page in options
=> Removed login FAQ message (Fixes #121, 4.0.6 release)

AuctionatorConfig.lua, Locales/ruRU.lua
Something of locale (I make comment with tag "not working") cannot be translated. You should check them in code. Like this https://github.com/Auctionator/Auctionator/blob/master/UI/Templates/Frames/Sell.xml#L605
=> Updated ruRU locale.

AuctionatorScanFull.lua
Fixes 
aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:733: attempt to index local 'color' (a nil value)
Taken from TSM ;)
=> Fix Blizzard error about color in full scan

Auctionator.lua, AuctionatorScan.lua
Added in lines to use library for item level display
=> libitemupgradeinfo change to fix itemlevel display

AuctionatorHints.lua
=> merchant stack fix

Auctionator.lua, Auctionator.toc, AuctionatorScanFull.lua, Libs/LibItemUpgradeInfo-1.0/Core.lua, UI/Templates/Frames/Sell.xml
* Version and TOC bump
* Updated to use new [SOUNDKIT constants](https://www.townlong-yak.com/framexml/ptr/SoundKitConstants.lua)
* Updated LibItemUpgradeInfo dependency
=> [Fixes 7.3 Issues] Sound Kit and misc updates

Auctionator.lua
Fixes being unable to post, updates deposits correctly, and in real-time when price is changed
=> Deposit and posting fixes

Auctionator.lua
nothing too important just some leaking global or unused locals
=> fix a couple variables

Auctionator.toc, AuctionatorVendor.lua
* Updated toc version for recent patch
* Applied fix suggested by @teyasio in #391 (unable to reproduce)
=> [Fixes #387] Mouseover bug fix

Source/Tooltips/Main.lua
=> Fix sellPrice is nil error when showing tooltip for non-items.

Source/Constants/DialogNames.lua, Source/Constants/Manifest.xml, Source/Events/AddonLoaded.lua, Source/Events/OnAuctionHouseClosed.lua, Source/Events/OnAuctionHouseShow.lua, Source/Events/ReplicateItemListUpdate.lua, Source/Manifest.xml, Source/Objects.lua, Source/ShoppingLists/Dialogs.lua, Source/ShoppingLists/Frame.xml, Source/ShoppingLists/Main.lua, Source/ShoppingLists/Manifest.xml, Source/ShoppingLists/Mixins.lua, Source/ShoppingLists/ResultsListMixins.lua, Source/ShoppingLists/ShoppingListMixins.lua, Source/ShoppingLists/Templates.xml, Source/Utilities/Manifest.xml, Source/Utilities/ToggleAuctionHouseTab.lua, Source/Variables/Main.lua
* Yay mixins
* This is a temp UI while we figure out how to display results
=> Basic shopping list implementation

Source/Core/AuctionatorAHFrame.xml, Source/Core/Mixin.lua, Source/FullScan/Mixins/Frame.lua, Source/ShoppingLists/Frame.xml, Source/ShoppingLists/Mixins/Dropdown.lua
* Adds button to manually begin an autoscan
* Reduces size of shopping list frame
=> [Fixes #503] Shopping List UI Updates

Source/Config/Frames/BasicOptions.xml, Source/Config/Frames/Selling.xml, Source/Config/Frames/Tooltips.xml, Source/Config/Mixins/Configuration.lua, Source/Events/OnAuctionHouseShow.lua
* Also saves config settings on panel change
=> [Fixes #526] Only create one AuctionatorAH Frame

Source/Constants/Main.lua, Source/Search/Main.lua, Source/Search/Manifest.xml, Source/ShoppingLists/Mixins/ScrollList.lua, Source/ShoppingLists/Mixins/ScrollListLine.lua, Source/Utilities/Manifest.xml, Source/Utilities/Slice.lua
The limit of 100 was determined by trial and error
=> [Fixes #536] Limit results from shopping list searches to avoid dcs

Source/Search/Advanced.lua, Source/Search/Manifest.xml, Source/Search/Mixins/AdvancedSearchProviderMixin.lua, Source/ShoppingLists/Mixins/ScrollListLine.lua
=> [Fixes #439] Pretty print of advanced search strings

Source/Database/Main.lua
Reworked other stuff, but never updated the naming conventions in this
file
=> Fix parameter names to itemKey instead of itemID in Database

Source/Core/AuctionatorAHFrame.xml, Source/Core/Mixin.lua, Source/Tabs/Auctionator/Frames/Main.xml, Source/Tabs/Auctionator/Mixins/Manifest.xml, Source/Tabs/Auctionator/Mixins/ScanButton.lua, Source/Tabs/ShoppingLists/Frames/Main.xml
* Moved FullScan button to auctionator tab
* Moved Create/Delete/Rename buttons on Shopping List tab to right of dropdown
=> [Fixes #651, Fixes #638] Moves some buttons around

Locales/enUS.lua, Source/ShoppingLists/Events.lua, Source/Tabs/DataProviders/ShoppingList.lua, Source/Tabs/ResultsListing/Mixins/ResultsListing.lua, Source/Tabs/ResultsListing/Templates/ResultsListing.xml
* also, display "no results" text
=> [Fixes #637] Hide spinner when no shopping list results found

Source/Components/Frames/MinMaxRangeGroup.xml, Source/Tabs/ShoppingLists/Frames/AddItem.xml, Source/Tabs/ShoppingLists/Mixins/AddItem.lua
* Add item dialog focuses search string on show
* MinMaxRange component now allows 6 characters (for price)
* Changed order of level and iLevel on add item dialog
=> [Fixes #668] Escape key now closes Add Item dialog

Source/Tooltips/Main.lua
Changes are 3 lines for an if statement and a return.
=> [Fixes #703] Auction tooltip setting now affects pet tooltips

Source/Search/Mixins/AdvancedSearchProviderMixin.lua
Such that "of fathoms" won't match "of the endless fathoms"
=> Change default search behaviour

Source/Tabs/Cancelling/Frames/Main.xml, Source/Tabs/Cancelling/Mixins/Buttons.lua, Source/Tabs/Cancelling/Mixins/Manifest.xml, Source/Tabs/DataProviders/Cancelling.lua, Source/Tabs/ResultsListing/Mixins/DeleteButtonCell.lua, Source/Tabs/ResultsListing/Mixins/Manifest.xml, Source/Tabs/ResultsListing/Templates/DeleteButtonCell.xml, Source/Tabs/ResultsListing/Templates/Manifest.xml
=> Added buttons for cancelling frame.

Source/Components/Frames/NumericInputBox.xml, Source/Components/Frames/RadioButton.xml, Source/Components/Mixins/NumericInputBox.lua, Source/Components/Mixins/RadioButton.lua, Source/Tabs/Selling/Frames/SaleItem.xml
Works fine ~~for current code, only issue is that it makes the 12/24/48 horizontal radio have the wrong text clicking for each item~~
=> Form text clicking

Locales/enUS.lua, Source/Config/Frames/BasicOptions.xml, Source/Config/Main.lua, Source/Config/Mixins/BasicOptions.lua, Source/Core/Mixin.lua
=> New options to change the default tab

Locales/enUS.lua, Source/Components/Frames/Manifest.xml, Source/Components/Frames/MoneyInputAlternate.xml, Source/Components/Frames/NumericInputBoxAlternate.xml, Source/Tabs/Selling/Frames/SaleItem.xml, Source/Tabs/Selling/Mixins/SaleItem.lua
=> [Fixes #794] Selling tab: Adjust text for quantity/price and add a "Max" button

Source/Variables/Main.lua
Long term sharing realm prices for connected realms is a great idea. Only caveat is that (worst case) a user may see months old prices until they do a scan (and after that things should be fine)
=> [Fixes #738] Share database on connected realms

Locales/enUS.lua, Source/Core/Mixin.lua, Source/Utilities/ClassicWoWCheck.lua, Source/Utilities/Manifest.xml
=> Add error message about classic support

Locales/enUS.lua, Source/SplashScreen/Mixins/Main.lua
Pending approval, I'm happy for the next release to be this one. There's enough QoL changes and bugfixes to make it worth releasing now, rather than waiting for the next big feature.
=> Added splash screen information for the 8.3.3 release

Source/Tabs/ResultsListing/Mixins/ShoppingListResultsRow.lua
Previously it would show an extra screen, requiring an extra click
=> Clicking on a shopping list result goes straight to the buy screen

Source/ShoppingLists/ImportExport.lua, Source/ShoppingLists/Main.lua, Source/ShoppingLists/Manifest.xml, Source/Tabs/ShoppingLists/Mixins/ImportFrame.lua
* TSM Groups
* Old-style Auctionator shopping lists
=> Add 2 new shopping list formats to import

Auctionator.toc, Locales/enUS.lua, Source/Config/Main.lua, Source/Events/VariablesLoaded.lua, Source/Manifest.xml, Source/Objects.lua, Source/PostingHistory/Manifest.xml, Source/PostingHistory/Mixin.lua, Source/Selling/Events.lua, Source/Tabs/DataProviders/HistoricalPrice.lua, Source/Tabs/DataProviders/Manifest.xml, Source/Tabs/DataProviders/PostingHistory.lua, Source/Tabs/ResultsListing/Mixins/Manifest.xml, Source/Tabs/ResultsListing/Mixins/PostingHistoryRow.lua, Source/Tabs/ResultsListing/Templates/Manifest.xml, Source/Tabs/ResultsListing/Templates/PostingHistoryRow.xml, Source/Tabs/Selling/Frames/Main.xml, Source/Tabs/Selling/Frames/Manifest.xml, Source/Tabs/Selling/Frames/MiniTabButton.xml, Source/Tabs/Selling/Mixins/HistoryContainerMixin.lua, Source/Tabs/Selling/Mixins/Main.lua, Source/Tabs/Selling/Mixins/Manifest.xml, Source/Tabs/Selling/Mixins/MiniTabButton.lua, Source/Tabs/Selling/Mixins/SaleItem.lua, Source/Variables/Main.lua
=> [Fixes #840] Show past posting prices

Source/Search/Advanced.lua, Source/Tabs/ShoppingLists/Mixins/Dropdown.lua, Source/Tooltips/Hooks.lua
I saw you cleaned up a "k" leak, here's a couple more.
=> Don't leak globals: result, listEntry, _

Locales/enUS.lua, Source/API/v1/MultiSearch.lua, Source/Search/Advanced.lua, Source/Tabs/Shopping/Frames/Item.xml, Source/Tabs/Shopping/Mixins/Item.lua, Source_Classic/CraftingInfo/Main.lua, Source_Classic/Search/Mixins/DirectSearchProviderMixin.lua, Source_Mainline/CraftingInfo/ObjectiveTracker.lua, Source_Mainline/CraftingInfo/Professions.lua, Source_Mainline/Search/Mixins/DirectSearchProviderMixin.lua, Source_Mainline/Tabs/Buying/Commodity/Mixins/Main.lua
From this:
to this: (after clicking the Search button)
with the 12 set to the quantity automatically
And the option in the extended search parameters to set your own quantities
=> Testing optional quantities to prepopulated for buying commodities on retail
